"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { FaBell, FaCalendarAlt, FaChartLine, FaExclamationTriangle, FaRobot, FaSearch, FaShieldAlt, FaSignOutAlt, FaSyncAlt, FaUsers } from "react-icons/fa";
import ProtectedPage from "@/components/ProtectedPage";
import { useAuth } from "@/components/AuthProvider";
import { apiFetch } from "@/lib/api";
import type { Booking, User, UserRole } from "@/lib/types";

interface AdminOverview { stats: { users: number; properties: number; bookings: number; pending: number; conversion_rate: number; no_shows: number }; recent_bookings: Booking[] }
const statusLabel: Record<string, string> = { WAITING_APPROVAL: "Chờ Sale", BOOKED: "Đã xác nhận", CANCELLED: "Đã hủy", REJECTED: "Bị từ chối", EXPIRED: "Hết hạn", APPROVED: "Đã duyệt" };
const statusStyle: Record<string, string> = { WAITING_APPROVAL: "bg-amber-50 text-amber-700", BOOKED: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-stone-100 text-stone-600", REJECTED: "bg-red-50 text-red-700", EXPIRED: "bg-red-50 text-red-700" };

function AdminDashboardContent() {
  const { user, logout } = useAuth();
  const router = useRouter();
  const [overview, setOverview] = useState<AdminOverview | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [query, setQuery] = useState("");
  const [role, setRole] = useState<UserRole | "">("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);

  const load = useCallback(async (quiet = false) => { if (!quiet) setLoading(true); try { setOverview(await apiFetch<AdminOverview>("/admin/overview")); if (user?.role === "ADMIN") setUsers(await apiFetch<User[]>(`/admin/users${role ? `?role=${role}` : ""}`)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không tải được dữ liệu vận hành"); } finally { if (!quiet) setLoading(false); } }, [role, user]);
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const interval = window.setInterval(() => void load(true), 20_000); return () => { window.clearTimeout(initial); window.clearInterval(interval); }; }, [load]);
  const visibleUsers = useMemo(() => users.filter((item) => `${item.full_name} ${item.email} ${item.phone ?? ""}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  const pipeline = useMemo(() => { const items = overview?.recent_bookings ?? []; return { waiting: items.filter((item) => item.status === "WAITING_APPROVAL").length, booked: items.filter((item) => item.status === "BOOKED").length, failed: items.filter((item) => ["REJECTED", "EXPIRED", "CANCELLED"].includes(item.status)).length }; }, [overview]);
  async function changeStatus(target: User) { const next = target.status === "ACTIVE" ? "LOCKED" : "ACTIVE"; if (!window.confirm(`${next === "LOCKED" ? "Khóa" : "Mở khóa"} tài khoản ${target.full_name}?`)) return; try { await apiFetch(`/admin/users/${target.id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); await load(true); } catch { setError("Không cập nhật được tài khoản."); } }
  async function handleLogout() { await logout(); router.replace("/login"); }

  return <div className="min-h-screen bg-[#f4f5f1] text-[var(--ink)] lg:flex">
    <aside className="bg-[var(--ink)] p-5 text-white lg:sticky lg:top-0 lg:min-h-screen lg:w-72"><div className="flex items-center gap-3 border-b border-white/10 pb-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10"><FaRobot className="text-[#a9c9b0]" /></span><div><p className="font-semibold">Nera Operations</p><p className="text-xs text-white/40">Control room</p></div></div><nav className="mt-6 space-y-2"><a href="#overview" className="flex items-center gap-3 rounded-xl bg-white/10 px-4 py-3 text-sm"><FaChartLine /> Sức khỏe hệ thống</a><a href="#bookings" className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm hover:bg-white/10"><FaCalendarAlt /> Booking pipeline</a>{user?.role === "ADMIN" && <a href="#users" className="flex items-center gap-3 rounded-xl px-4 py-3 text-sm hover:bg-white/10"><FaUsers /> Người dùng</a>}</nav><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[#a9c9b0]"><FaShieldAlt /> Hệ thống</p><p className="mt-3 flex items-center gap-2 text-sm"><i className="h-2 w-2 rounded-full bg-emerald-400" /> API đang hoạt động</p><p className="mt-2 text-xs text-white/40">Tự làm mới mỗi 20 giây</p></div><button onClick={() => void handleLogout()} className="mt-6 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm text-[#e8a58d] hover:bg-white/10"><FaSignOutAlt /> Đăng xuất</button></aside>
    <main className="min-w-0 flex-1 p-4 sm:p-8 xl:p-10"><header id="overview" className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--coral)]">Trung tâm vận hành</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Quan sát vấn đề trước khi khách gặp phải.</h1><p className="mt-2 text-sm text-[var(--muted)]">Xin chào {user?.full_name}. Số liệu lấy trực tiếp từ luồng booking và tài khoản.</p></div><button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-full border border-black/10 bg-white px-4 py-2.5 text-sm font-semibold"><FaSyncAlt className={loading ? "animate-spin" : ""} /> Làm mới</button></header>
      {error && <div role="alert" className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
      <section className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Tổng booking", value: overview?.stats.bookings, note: "Toàn bộ yêu cầu", icon: FaCalendarAlt }, { label: "Đang chờ Sale", value: overview?.stats.pending, note: "Cần theo dõi SLA", icon: FaBell }, { label: "Tỷ lệ xác nhận", value: overview ? `${overview.stats.conversion_rate}%` : undefined, note: "Booking chuyển thành lịch", icon: FaChartLine }, { label: "No-show", value: overview?.stats.no_shows, note: "Cần gọi lại khách", icon: FaExclamationTriangle }].map(({ label, value, note, icon: Icon }, index) => <div key={label} className={`rounded-[1.5rem] p-5 shadow-sm ${index === 1 && Number(value) > 0 ? "bg-[#fff1e8]" : "bg-white"}`}><div className="flex items-center justify-between"><p className="text-sm text-[var(--muted)]">{label}</p><Icon className={index === 1 ? "text-[var(--coral)]" : "text-[var(--forest)]"} /></div><p className="mt-3 text-4xl font-semibold">{value ?? "–"}</p><p className="mt-2 text-xs text-[var(--muted)]">{note}</p></div>)}</section>
      <div className="mb-8 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-[1.6rem] bg-[var(--forest)] p-6 text-white"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#bcd2c1]">Cảnh báo vận hành</p><h2 className="mt-2 text-xl font-semibold">{overview?.stats.pending ? `${overview.stats.pending} yêu cầu đang chờ phản hồi` : "Không có cảnh báo khẩn"}</h2><p className="mt-3 text-sm leading-6 text-white/60">{overview?.stats.pending ? "Theo dõi yêu cầu sắp hết hạn; hệ thống sẽ tự phân Sale khác nếu cần." : "Luồng phân Sale và xác nhận lịch đang trong ngưỡng bình thường."}</p><div className="mt-5 flex gap-3"><a href="#bookings" className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-[var(--forest)]">Mở pipeline</a><span className="rounded-full border border-white/15 px-4 py-2 text-xs text-white/70">{overview?.stats.no_shows ?? 0} no-show</span></div></section><section className="rounded-[1.6rem] border border-black/5 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[var(--coral)]">Pipeline gần đây</p><h2 className="mt-2 text-xl font-semibold">Từ yêu cầu đến lịch xem</h2></div><FaChartLine className="text-[var(--forest)]" /></div><div className="mt-6 grid grid-cols-3 gap-3">{[["Chờ Sale", pipeline.waiting, "bg-amber-400"], ["Đã đặt", pipeline.booked, "bg-emerald-500"], ["Không thành công", pipeline.failed, "bg-red-400"]].map(([label, value, color]) => <div key={String(label)}><div className={`h-2 rounded-full ${color}`} /><p className="mt-3 text-2xl font-semibold">{value}</p><p className="text-xs text-[var(--muted)]">{label}</p></div>)}</div></section></div>
      <section id="bookings" className="mb-10"><div className="mb-4"><p className="text-xs font-bold uppercase tracking-[.15em] text-[var(--coral)]">Live operations</p><h2 className="mt-1 text-xl font-semibold">Booking gần đây</h2></div><div className="overflow-x-auto rounded-[1.5rem] border border-black/5 bg-white shadow-sm"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-[#f7f7f3] text-[var(--muted)]"><tr><th className="p-4">Yêu cầu</th><th className="p-4">Khách hàng</th><th className="p-4">Nhà quan tâm</th><th className="p-4">Sale phụ trách</th><th className="p-4">Trạng thái</th></tr></thead><tbody className="divide-y divide-black/5">{overview?.recent_bookings.map((booking) => <tr key={booking.id} className="transition hover:bg-[#fbfaf7]"><td className="p-4 font-mono text-xs">{booking.request_code}</td><td className="p-4 font-medium">{booking.customer?.full_name}<br /><span className="text-xs font-normal text-[var(--muted)]">{booking.customer?.phone ?? booking.customer?.email}</span></td><td className="max-w-xs p-4"><span className="line-clamp-2">{booking.property.title}</span></td><td className="p-4">{booking.sale?.full_name ?? <span className="text-[var(--coral)]">Chưa gán</span>}</td><td className="p-4"><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${statusStyle[booking.status] ?? "bg-stone-100"}`}>{statusLabel[booking.status] ?? booking.status}</span></td></tr>)}{overview?.recent_bookings.length === 0 && <tr><td colSpan={5} className="p-10 text-center text-[var(--muted)]">Chưa có booking.</td></tr>}</tbody></table></div></section>
      {user?.role === "ADMIN" && <section id="users"><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[var(--coral)]">Access control</p><h2 className="mt-1 text-xl font-semibold">Người dùng hệ thống</h2><p className="mt-1 text-xs text-[var(--muted)]">{overview?.stats.users ?? users.length} tài khoản · {overview?.stats.properties ?? 0} căn trong kho</p></div><div className="flex gap-2"><label className="relative"><span className="sr-only">Tìm người dùng</span><FaSearch className="absolute left-3 top-3 text-[var(--muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="rounded-xl border border-black/10 bg-white py-2 pl-9 pr-3 text-sm" placeholder="Tên, email, SĐT" /></label><select aria-label="Lọc vai trò" value={role} onChange={(event) => setRole(event.target.value as UserRole | "")} className="rounded-xl border border-black/10 bg-white px-3 text-sm"><option value="">Tất cả vai trò</option><option value="CUSTOMER">Khách hàng</option><option value="SALE">Sale</option><option value="COORDINATOR">Điều phối</option><option value="ADMIN">Admin</option></select></div></div><div className="overflow-x-auto rounded-[1.5rem] border border-black/5 bg-white shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#f7f7f3] text-[var(--muted)]"><tr><th className="p-4">Người dùng</th><th className="p-4">Vai trò</th><th className="p-4">Điện thoại</th><th className="p-4">Trạng thái</th><th className="p-4">Thao tác</th></tr></thead><tbody className="divide-y divide-black/5">{visibleUsers.map((item) => <tr key={item.id} className="hover:bg-[#fbfaf7]"><td className="p-4 font-medium">{item.full_name}<br /><span className="font-normal text-[var(--muted)]">{item.email}</span></td><td className="p-4">{item.role}</td><td className="p-4">{item.phone || "–"}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.status === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{item.status}</span></td><td className="p-4"><button disabled={item.id === user.id || item.status === "DISABLED"} onClick={() => void changeStatus(item)} className="rounded-full border border-black/10 px-3 py-1.5 text-xs font-semibold disabled:opacity-40">{item.status === "ACTIVE" ? "Khóa" : "Mở khóa"}</button></td></tr>)}</tbody></table></div></section>}
    </main>
  </div>;
}

export default function AdminDashboard() { return <ProtectedPage roles={["ADMIN", "COORDINATOR"]}><AdminDashboardContent /></ProtectedPage>; }
